### ISSUE TITLE
regarding the onlybase flag

### ISSUE THREAD

**Issue by tumble-weed** [sjtuzq/point-radiance#1]
Hello,
thank you for your work and making the implementation open source. i had a question regarding the onlybase flag here (https://github.com/sjtuzq/point-radiance/blob/501158f58b70ea38b11f06715be8435cb09f8df8/modules/model.py#L92) . it seems that the ```renderer``` is able to make an image using the ```cameras``` variable which has information regarding the pose. however if ```onlybase``` is False, we also do an evaluation of the spherical harmonics. so without ```onlybase``` are we doing an approximation of the lighting, kind of like using the "lower frequency" components. and is this for stabilizing the training of the parameters at earlier stages?

**Comment by sjtuzq** [comment]
This onlybase flag means that for each point, there are no spherical harmonic parameters, but the color parameters instead. The color can also be viewed as the base spherical harmonics with a degree of 0.

**Comment by tumble-weed** [comment]
thank you.
